### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by NotFoundDC** [TermiT/Flycut#45]
In Mavericks, when using multiple monitors, flycut will always paste your text on the first monitor, even when you're working on the second monitor.

**Comment by scottharr27** [comment]
Using OS X 10.10.1 (14B25) and this issue is back. Please fix!

**Comment by MarkJerde** [comment]
Just speculating, it sounds like Apple may have a focus retention bug, where they remember what application was focused but not which window, perhaps gravitating to a window of that app on the screen the bezel was on. An analogous operation may be to open app X on both monitors, focused on monitor B; open one window of app Y on monitor A; close Y; see if focus returns to X on A or returns to X but on B. Is this that old App Store version or some other build? You could look at the bezel display/hide code to see if there's a way to direct the bezel to a particular display and/or detect which window was active before the bezel gets opened. 

Best of luck,
Mark

**Comment by scottharr27** [comment]
I'm using Version 1.5 (1.5) from the App Store. Is there an updated version
I can try somewhere?

I'm not a developer so I don't know how to try any of your suggestions... :(

**Comment by gavJackson** [comment]
+1 for Flycut Bezel displaying on the monitor the current focus is on.

(Paste works fine with multiple monitors)

**Comment by AvdLee** [comment]
+1, also experiencing this issue.

**Comment by maxx555** [comment]
+1, also experiencing this issue.

**Comment by jkee** [comment]
About same issue for me.
Flycut window is always displayed on one monitor and newer on second one.

**Comment by nlyonssmith** [comment]
+1 also experiencing this issue.

**Comment by jayb904** [comment]
+1 - having this issue as well. I have 2 monitors connected to my MBP via Thunderbolt and the bezel is always displayed on the MBP screen regardless of which monitor has focus. OSX 10.11.4

**Comment by hungri-yeti** [comment]
Just to add another data point, I'm not seeing this issue on Mid-2009 MBP (10.11.3) with DVI external monitor. Bezel appears on focused monitor, text is pasted into focused window as expected.

**Comment by MarkJerde** [comment]
jayb904 -
The problem you describe was fixed in #71 about a year ago. Are you using a really old build or the App Store version that hasn't been updated in about five years?
- Mark

**Comment by jayb904** [comment]
Looks like I'm using 1.5 from the App Store.

**Comment by scottharr27** [comment]
@jayb904 @MarkJerde How do I install the GH version on my Mid 2014 MBP running 10.11.4?

**Comment by scottharr27** [comment]
I was able to install 1.7 from GH today, but it wouldn't paste anything from the app?

**Comment by MarkJerde** [comment]
Since it isn't clear that either of the problems discussed in this thread still exist in an up-to-date build, I suggest that any interested parties try to reproduce the "pastes on wrong monitor" bug with the following build ( https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-Master-2016.03.30.tgz?raw=true ) and respond by the end of April 2016 if it still exists.  Beyond that date we should consider the issue closed.

Thanks,
Mark

**Comment by scottharr27** [comment]
@MarkJerde I used your build and can still reproduce the "pastes on wrong monitor" bug. Screencast here: https://www.dropbox.com/s/gy1xw9fa8erq5jk/FlyCutSecondMonitorBug.mov?dl=0

The bug exists when trying to paste to Chrome. It doesn't exist in TextEdit.

**Comment by scottharr27** [comment]
Confirming this is still an issue (with at least Chrome Version 49.0.2623.110 (64-bit)) and Flycut Version 1.8 (1.82f0187.35.1604).

**Comment by wifiprintguy** [comment]
Having this issue as well.  I just switched from a very old copy of Jumpcut to Flycut off the App Store (version 1.5, a bit behind the HEAD branch on GitHub).  This was a long standing problem with Jumpcut, and although I know this is a fork, I was hoping the issue was resolved. 😞 

No problems with TextEdit, BBEdit, but it IS reproducible with Apple Mail.  And it is only reproducible if Mail has open windows on both displays.

MacBookPro8,2
1 external monitor (HP ZR30w) connected via DisplayPort

**Comment by MarkJerde** [comment]
@wifiprintguy - The App Store version is five years (and very many changes) behind the HEAD. You could try with the build linked above or the one linked in the readme.

**Comment by scottharr27** [comment]
@MarkJerde @wifiprintguy this is still an issue with Flycut Version 1.8 (1.82f0187.35.1604). Please see my screencast: https://www.dropbox.com/s/gy1xw9fa8erq5jk/FlyCutSecondMonitorBug.mov?dl=0

**Comment by MarkJerde** [comment]
Thanks, Scott.
I finally encountered this bug myself.  It sure is annoying.  Here's my setup (for documentation).

OS X Yosemite
MacBook Pro Retina 15
Internal display plus two externals (displayPort and DVI)
Mail.app main window open on built-in display.  Message reply (edit) window on secondary display.
Type message... switch to other app... copy data... copy other data... switch to Mail.app... activate Flycut bezel... navigate and select via 'return'... focus returned to mail main window, with useless paste...  repeat many times... get annoyed.

I'll see if I can find some time to debug this a bit.
- Mark

**Comment by scottharr27** [comment]
@MarkJerde so happy you were able to replicate the bug and that you're willing to debug. I really hope a fix can be compiled into a DRM-Free download soon as I encounter this bug every day. :)

**Comment by MarkJerde** [comment]
Tried it on my dev system and couldn't reproduce the bug.  This is where detailed system information gets useful.

Didn't reproduce on:
OS X Mavericks (10.9.5)
MacBook Pro 15 Mid-2010
Tested with Mail.app typing an email on each screen and selecting through the Flycut bezel.

@scottharr27 (and anybody else encountering this) Could you add your OS and hardware specs?  Thanks

**Comment by scottharr27** [comment]
Reproduced on:
OS X El Capitan (10.11.4)
MacBook Pro Retina, 13-inch, Mid 2014

**Comment by ranvel** [comment]
I am seeing this on 15 rMBP, Late 2015, El Capitan, 10.11.5

I was having the issue with the App Store version, but it was having this bug. I found this Github version (thank you!)  and it continued to happen. I use this app constantly and I feel like the issue went away for a few builds of 10.11.x. It's back now.

**Comment by Siddhartha90** [comment]
Also having this issue, works with only one window of an application open, does not work when it's open on more than one monitor. It'll always try and paste to the main monitor 😫

**Comment by whitingj** [comment]
I've had the same issue when using Chrome.  I'll attempt to find a way to reproduce and put my steps here if I can it it to consistently to reproduce.

**Comment by whitingj** [comment]
It seems to be application specific.  I can reproduce it in Chrome but not in Firefox.  I can repro this without actually doing a paste.

Steps to repro:
1. Open up 2 chrome windows
2. Move one window to your primary monitor and the other one to your secondary monitor
3. Focus the windows on your secondary monitor
4. Press your hotkey to bring up the flycut modal.
- Notice that no Chrome window has focus. It appears the popup the flycut modal has focus.
5. Press "esc"

Results:
The focus is now on the OTHER Chrome window on the main monitor.  If I had done a paste it would have attempted to paste in that window rather than the one I initiated the paste on.

Expected Results:
The focus stays on the window I initiated the paste from.  

Observation:
An interesting observation, when using spotlight or alfred when it pops up its modal the Chrome window doesn't loose focus, it is still selected.

**Comment by whitingj** [comment]
I think the key is to set this mask when creating the flycut modal:
NSNonactivatingPanelMask
(see http://stackoverflow.com/questions/21326958/cast-nswindow-to-nspanel)

Rather the using a NSWindow it looks like you'd have to use a NSPanel.

**Comment by MarkJerde** [comment]
@whitingj - Wow, Jeff.  It's not every day that someone walks in out of the blue and hands you the solution to a 2+ year old bug.  The world needs more people like you.  I put your idea in (something like three lines) and did a build of it to test on my system that was showing the problem.  It seems to perfectly fix the problem without any side-effects noticed yet.

Anybody who wants to try the beta to see if it fixes their problem can download it from [https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-Issue45-Beta.tgz?raw=true](https://github.com/MarkJerde/LMBTFY/blob/master/Flycut-Issue45-Beta.tgz?raw=true).  This build uses the Flycut preferences/save in ~/Library/Preferences/com.generalarcade.flycut.plist (this moves around depending on code-signing settings, so documented here so you don't have trouble losing your clippings list).

I'll beta test it a bit before doing a pull request.  Jeff, if you'd like to make the fix or like me to try putting it in with your name on it let me know, since you're really the one who contributed the solution.

Thanks,
Mark

**Comment by TermiT** [comment]
@whitingj & @MarkJerde nice job, guys!

**Comment by whitingj** [comment]
Glad I was able to help!  After doing the initial research I was meaning to put together a patch but I just haven't had a chance.  I'll try to create a pull request this weekend.

**Comment by MarkJerde** [comment]
Oddly, I still encountered the bug today and was using the new build as best as I could tell. I didn't have time to look into it further, so I'm just confused at this point and didn't want anybody else to be confused if they were still seeing the problem. Let us know if you try it and find it does fix things. 
- Mark

**Comment by JoelStickney** [comment]
Where are the lines you added / changed to try and mirror Quicksilver's window management, thinking about doing some experiments on this, but the 'latest' build you lined above doesn't seem to be committed just yet (at least I didn't see any commit logs for it).

**Comment by whitingj** [comment]
@JoelStickney I've made the changes in my repo: https://github.com/whitingj/Flycut.  I haven't had a chance to verify the changes yet but you are welcome to try it out.

**Comment by whitingj** [comment]
Pull request #113 should fix this issue.  It would be great if people could try it out and let me know if it fixes their problems.

**Comment by davidwagnerkc** [comment]
@whitingj I compiled the latest commit today and I has been working perfectly since I began work this morning. Appreciate you taking the time to fix this issue, it was really interrupting my workflow! (Also, sorry if I am not supposed to comment on a closed issue. I'm not too familiar with the GitHub process for this.)

**Comment by dwagnerkc** [comment]
@whitingj It has resolved the issue for me. I compiled the latest commit this morning and have been using it since then. I have a MacBookPro with two external monitors. Really appreciate your fix, it was very frustrating dealing with multiple monitors before! (Also, sorry if I am not supposed to comment on a closed issue; I'm not too familiar with the GitHub process for this, just wanted to let you know.)

**Comment by scottharr27** [comment]
So awesome to hear! Can someone post an updated DRM version here? https://github.com/TermiT/Flycut/releases

**Comment by whitingj** [comment]
I'm glad it's fixed your problems! 

I'll have to defer to someone else to get a new version published on github.

**Comment by TermiT** [comment]
@scottharr27 I need to test it a bit, and later I release an update

**Comment by huylv** [comment]
@TermiT Are we ready for a new release?

**Comment by whitingj** [comment]
Hey can we get a release?  IMO this issue is a really nice fix and solves a lot of outstanding issues.

**Comment by erikforss** [comment]
Hey guys, I guess this hasn't been released yet?
Still facing this issue on a MacBook Air with High Sierra 10.13.6.
A release with the fix would be a blast, love your tool!

**Comment by MarkJerde** [comment]
Looks like someone comment asking for the release and then deleted it, so I'll just close the loop here.

This is in the 1.8.1 (Oct 2016) and later releases here: https://github.com/TermiT/Flycut/releases

**Comment by deepakmarathe** [comment]
this helped my issue 
https://osxdaily.com/2010/04/27/set-the-primary-display-mac/
